### ISSUE TITLE
Move multiple windows of the same program

### ISSUE THREAD

**Issue by MNolan147** [Nama/sway-workspaces#3]
Currently, the script doesn't know what to do when there are multiple windows of the same program that need to be arranged.

**Comment by Nama** [comment]
Implemented @roselandgoose code with 7580bc1f9151d2980c0ccd635b1822c1824675cd.

Window titles are compared. That means, that if you have another website open in your browser, it wont be possible to match. But then it still moves them separately to the correct workspaces. Might just be the wrong windows^^
